name: 'Deploy'
on:
    workflow_call:
      inputs:
        TARGET_ENV:
          required: true
          type: string
jobs:
  job-to-run-per-env:
    name: 'Job to run per env'
    runs-on: ubuntu-latest
    environment: ${{ inputs.TARGET_ENV }}        
    steps:
      - name: Variable
        shell: bash
        run:  echo " ${{ vars.NAME }}"
      - name: Secret
        shell: bash
        run:  echo " ${{ secrets.AZURE_CLIENT_ID }}"