name: 'Deploy'
on:
    workflow_call:
      inputs:
        NAME:
          required: true
          type: string

jobs:
  job-to-run-per-env:
    name: 'Job to run per env'
    runs-on: ubuntu-latest        
    steps:
      - name: Any Name
        shell: bash
        run:  echo " ${{ inputs.NAME }}"