name: 'Deploy'
on:
    workflow_call:
      inputs:
        TARGET_ENV:
          required: true
          type: string
      secrets:
        AZURE_CLIENT_ID: 
          required: true
      

jobs:
  job-to-run-per-env:
    name: 'Job to run per env'
    environment: ${{ inputs.TARGET_ENV }}
    runs-on: ubuntu-latest        
    steps:
      - name: Any Name
        shell: bash
        run:  echo " ${{ secrets.AZURE_CLIENT_ID }}"