name: 'Demo'
on:
  push:
    branches:
    - main

jobs:
  dev:
    runs-on: ubuntu-latest
    environment: dev
    steps:
      - uses: ./.github/workflows/deploy.yaml
        with:
          NAME: ${{ env.NAME }}
  sandbox:
    runs-on: ubuntu-latest
    environment: sandbox
    steps:
      - uses: ./.github/workflows/deploy.yaml
        with:
          NAME: ${{ env.NAME }}