name: 'Demo'
on:
  push:
    branches:
    - main

jobs:
  dev:
    uses: ./.github/workflows/deploy.yaml
    with:
      TARGET_ENV: dev
  sandbox:
    uses: ./.github/workflows/deploy.yaml
    needs: [dev]
    with:
      TARGET_ENV: sandbox
