name: 'Demo'
on:
  push:
    branches:
    - main

jobs:
  dev:
    runs-on: ubuntu-latest
    environment: dev
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: ./.github/workflows/deploy.yaml
        with:
          NAME: ${{ env.NAME }}
  sandbox:
    runs-on: ubuntu-latest
    environment: sandbox
    needs: [dev]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: ./.github/workflows/deploy.yaml
        with:
          NAME: ${{ env.NAME }}