name: 'Demo'
on:
  push:
    branches:
    - main

jobs:
  job-to-run-per-env:
    name: 'Job to run per env'
    environment: ${{ matrix.environment }}
    runs-on: ubuntu-latest    
    strategy:
      matrix:
        # We need to run this on all the environments
        environment: [sandbox, dev]
        
    steps:
      - name: Any Name
        shell: bash
        run:  echo "Hello World"